//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment_2 {
	
	
	public partial class adminpage {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Panel Login_panel;
		
		protected System.Web.UI.WebControls.TextBox username;
		
		protected System.Web.UI.WebControls.TextBox password;
		
		protected System.Web.UI.WebControls.Label Login_false;
		
		protected System.Web.UI.WebControls.Panel Login_true;
		
		protected System.Web.UI.WebControls.FileUpload FileUploadControl;
		
		protected System.Web.UI.WebControls.Label ValidFile;
		
		protected System.Web.UI.WebControls.Button CoffeeButton;
	}
}
